### ISSUE TITLE
Grammar sections are missing some data. 

### ISSUE THREAD

**Issue by johnjung** [johnjung/lucy#11]
Looking at the XML data for lesson one:
http://ochre.lib.uchicago.edu/ochre?uuid=0ad43a89-09d6-4292-88cb-b6fd6dfe41e5

I see some data for the first part of the grammar section in lesson one: the string "In the phrases" appears in the XML data. However, other parts of this grammar section do not appear. For example, the string "Here, too" occurs on the static site, but not in the XML data. 

Can you tell what's going on here?

**Comment by MillerPr** [comment]
Hi John, this is slightly more complicated in that the grammar content is stored as a separate document. You can access using the UUID of the linked item. I'll try to post a picture here:
![image](https://user-images.githubusercontent.com/38267557/64282468-1da61100-cf1b-11e9-995a-7c8917da76c8.png)
That UUID will point you to a resource type XML document. There, you will find the grammar in a document element:
![image](https://user-images.githubusercontent.com/38267557/64282547-4b8b5580-cf1b-11e9-9228-c0cbd0b50497.png)
Let me know if that causes any problems on your end.

**Comment by johnjung** [comment]
That works for me. For lesson one that adds six http requests, but the loading time for the website is still very quick.

I do see that some Grammar sections are currently unpublished, like lessons two and three. Are those ready to be published? Please let me know if I can send along any more details.

**Comment by MillerPr** [comment]
Do you mean that the Grammar sections are not showing up in the Lesson 02 xml document? Or are there instances in which you are making an API call to a specific discourse unit that represents a Grammar section?

**Comment by MillerPr** [comment]
Or maybe you mean that the linked documents are not all published. That may well have been the case. I just published them all. Let me know if you find any that escaped my query and remain unpublished.

**Comment by johnjung** [comment]
This looks great now. Thank you!
