### ISSUE TITLE
Where is data for Drills in lesson one? 

### ISSUE THREAD

**Issue by johnjung** [johnjung/lucy#12]
The data for lesson one's drills appears to be missing. Here is the XML for lesson one:
http://ochre.lib.uchicago.edu/ochre?uuid=0ad43a89-09d6-4292-88cb-b6fd6dfe41e5

On the static site, the first drill includes the string "You greet a friend". This string does not appear in the XML. Do parts of these lessons need to be published?

**Comment by MillerPr** [comment]
I rebuilt the XML paths in OCHRE and republished the lesson. These nodes are now appearing in the published XML. Let me know if any others have this problem. Thanks.

**Comment by johnjung** [comment]
Excellent! Thanks very much- closing this issue out.
