### ISSUE TITLE
Lesson Five, Basic Sentences missing 4a, 4b, 4c

### ISSUE THREAD

**Issue by johnjung** [johnjung/lucy#13]
Here is the data for lesson five:
http://ochre.lib.uchicago.edu/ochre?uuid=db7cbbe1-229f-4b60-a8f1-35fda8ec9dbd

On the static site, sentence 4 is broken down into three separate sentences: 4a, 4b, and 4c. This currently does not appear in the backend data. Additionally, numbering for basic sentences is currently calculated based on the position of each section in the XML data- if we would like to maintain the labelling for sentences 4a, 4b, and 4c, this should appear in the backend data as well.

**Comment by MillerPr** [comment]
You are correct. The same appears to be true for lesson 7, sentence 10. I will update you when this is fixed and republished.

**Comment by MillerPr** [comment]
These have been corrected and republished in OCHRE. Hopefully this solves the problem.

**Comment by johnjung** [comment]
The sentences in lesson five look good, but I don't see lesson seven, sentence 10b in the data. The English translation includes the string "what's the name of that thing?". I don't find the characters "(space)thing?" in the data. 

Please take a look when you have a chance.

**Comment by MillerPr** [comment]
Error corrected and republished. Thanks!

**Comment by johnjung** [comment]
Closing this issue out. Thank you!
