### ISSUE TITLE
Lesson Five, basic sentence 4 transcription sound clip unpublished?

### ISSUE THREAD

**Issue by johnjung** [johnjung/lucy#14]
Lesson five XML:
http://ochre.lib.uchicago.edu/ochre?uuid=db7cbbe1-229f-4b60-a8f1-35fda8ec9dbd

The transcription for lesson five, basic sentences, sentence 4 is "Maʾalob, jeʾ a kanikeʾexeʾ". Searching for that string in the XML shows that a corresponding links/resource[@type="audio"] element does not currently appear. Does this element need to be published? 

See also, lesson 7, basic sentences, sentence 10.

**Comment by MillerPr** [comment]
It appears that the a, b, c affixes caused an issue on import, or perhaps they were not properly organized in the legacy data. In any case, lesson five 4a-c have been combined into a single sentence. The same is true for lesson 7, sentence 10. The OCHRE team will need to untangle the data in OCHRE, link the appropriate audio clips, and republish. I will update you when this is complete.

**Comment by MillerPr** [comment]
Lesson 5, sentences 4a-c and Lesson 7, sentence 10 are  now properly configured in OCHRE and republished. Let me know if you notice any issues with these.

**Comment by johnjung** [comment]
Thank you! This looks good. Closing this issue out.
